const allEvents = [
    {
    
      title: "Tech Innovators Summit",
      img: "https://images.unsplash.com/photo-1522158637959-30385a09e0da?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      description: "An event for exploring the latest in tech innovations.",
      location: "San Francisco, CA",
      date: new Date("2025-03-15"),
      organizer_name: "InnovateX",
      is_free: false,
      ticket_price: 50,
      registration_link: "https://event1.com/register",
    },
    {
      title: "Art & Soul Festival",
      img: "https://images.unsplash.com/photo-1522158637959-30385a09e0da?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      description: "A colorful gathering celebrating local art and music.",
      location: "Austin, TX",
      date: new Date("2025-04-07"),
      organizer_name: "ArtHouse Co.",
      is_free: true,
    },
    {
      title: "Green Earth Workshop",
      img: "https://images.unsplash.com/photo-1522158637959-30385a09e0da?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      description: "Learn sustainable practices to protect our planet.",
      location: "Portland, OR",
      date: new Date("2025-04-22"),
      organizer_name: "EcoChange",
      is_free: true,
    },
    {
      title: "Startup Pitch Night",
      img: "https://example.com/event4.jpg",
      description: "Entrepreneurs pitch to top investors in the industry.",
      location: "New York, NY",
      date: new Date("2025-05-05"),
      organizer_name: "Founders Hub",
      is_free: false,
      ticket_price: 20,
      registration_link: "https://event4.com/register",
    },
    {
      title: "Code Camp 2025",
      img: "https://example.com/event5.jpg",
      description: "A bootcamp for developers to upskill and network.",
      location: "Seattle, WA",
      date: new Date("2025-07-01"),
      organizer_name: "CodeStream",
      is_free: false,
      ticket_price: 75,
      registration_link: "https://codecamp2025.com/register",
    },
    {
      title: "Wellness & Yoga Retreat",
      img: "https://example.com/event6.jpg",
      description: "Relax and rejuvenate with yoga, meditation, and wellness talks.",
      location: "Sedona, AZ",
      date: new Date("2025-08-20"),
      organizer_name: "Zen Life",
      is_free: false,
      ticket_price: 100,
      registration_link: "https://zenretreat.com",
    },
    {
      title: "AI Future Talk",
      img: "https://example.com/event7.jpg",
      description: "Exploring artificial intelligence and its impact on society.",
      location: "Boston, MA",
      date: new Date("2025-05-30"),
      organizer_name: "AI World",
      is_free: true,
    },
    {
      title: "Food Carnival Fiesta",
      img: "https://example.com/event8.jpg",
      description: "Taste delicious dishes from around the world.",
      location: "Los Angeles, CA",
      date: new Date("2025-06-25"),
      organizer_name: "Tasty Events",
      is_free: false,
      ticket_price: 10,
      registration_link: "https://foodcarnival.com/register",
    },
    {
      title: "Blockchain Expo",
      img: "https://example.com/event9.jpg",
      description: "An immersive experience into blockchain tech.",
      location: "Miami, FL",
      date: new Date("2025-09-10"),
      organizer_name: "CryptoSpace",
      is_free: true,
    },
    {
      title: "Digital Marketing Meetup",
      img: "https://example.com/event10.jpg",
      description: "A networking event for digital marketing pros.",
      location: "Chicago, IL",
      date: new Date("2025-07-18"),
      organizer_name: "MarketMinds",
      is_free: true,
    },
  
    // 20 more events below
  
    {
      title: "Photography Walk",
      img: "https://example.com/event11.jpg",
      description: "Capture the city's hidden gems through your lens.",
      location: "Denver, CO",
      date: new Date("2025-06-12"),
      organizer_name: "SnapIt",
      is_free: true,
    },
    {
      title: "FinTech Roundtable",
      img: "https://example.com/event12.jpg",
      description: "Discussing innovations in the financial tech space.",
      location: "New York, NY",
      date: new Date("2025-10-05"),
      organizer_name: "Finance Now",
      is_free: false,
      ticket_price: 40,
      registration_link: "https://fintechround.com",
    },
    {
      title: "Women in Tech Conference",
      img: "https://example.com/event13.jpg",
      description: "Empowering women to lead in tech.",
      location: "San Diego, CA",
      date: new Date("2025-05-20"),
      organizer_name: "TechLadies",
      is_free: true,
    },
    {
      title: "Mindfulness Matters",
      img: "https://example.com/event14.jpg",
      description: "Practice mindfulness and reduce stress in daily life.",
      location: "Richmond, VA",
      date: new Date("2025-09-09"),
      organizer_name: "CalmFlow",
      is_free: true,
    },
    {
      title: "Startup Expo 2025",
      img: "https://example.com/event15.jpg",
      description: "A place to discover exciting new startups.",
      location: "Atlanta, GA",
      date: new Date("2025-11-11"),
      organizer_name: "StartX",
      is_free: false,
      ticket_price: 30,
      registration_link: "https://startupexpo.com/register",
    },
    {
      title: "VR and Gaming Fest",
      img: "https://example.com/event16.jpg",
      description: "Experience the future of gaming and VR.",
      location: "San Jose, CA",
      date: new Date("2025-12-01"),
      organizer_name: "GameZone",
      is_free: false,
      ticket_price: 60,
      registration_link: "https://vrfest.com",
    },
    {
      title: "Ocean Awareness Seminar",
      img: "https://example.com/event17.jpg",
      description: "Learn how to protect our oceans and marine life.",
      location: "Honolulu, HI",
      date: new Date("2025-06-08"),
      organizer_name: "BlueEarth",
      is_free: true,
    },
    {
      title: "Tech for Good Hackathon",
      img: "https://example.com/event18.jpg",
      description: "Build solutions that solve real-world problems.",
      location: "Austin, TX",
      date: new Date("2025-08-11"),
      organizer_name: "DevImpact",
      is_free: false,
      ticket_price: 15,
      registration_link: "https://techforgood.com",
    },
    {
      title: "Public Speaking Mastery",
      img: "https://example.com/event19.jpg",
      description: "Develop confidence and clarity in your voice.",
      location: "Philadelphia, PA",
      date: new Date("2025-05-12"),
      organizer_name: "SpeakUp",
      is_free: true,
    },
    {
      title: "Space Exploration Talk",
      img: "https://example.com/event20.jpg",
      description: "A deep dive into the future of space travel.",
      location: "Houston, TX",
      date: new Date("2025-09-25"),
      organizer_name: "Galactic Talks",
      is_free: true,
    },
    {
      title: "Community Coding Challenge",
      img: "https://example.com/event21.jpg",
      description: "Compete and collaborate on fun coding problems.",
      location: "Columbus, OH",
      date: new Date("2025-06-05"),
      organizer_name: "CodeCircle",
      is_free: false,
      ticket_price: 10,
      registration_link: "https://codechallenge.com",
    },
    {
      title: "Mental Health Matters",
      img: "https://example.com/event22.jpg",
      description: "Raising awareness and offering support resources.",
      location: "Nashville, TN",
      date: new Date("2025-05-22"),
      organizer_name: "MindCare",
      is_free: true,
    },
    {
      title: "SaaS Product Launches",
      img: "https://example.com/event23.jpg",
      description: "Discover the latest SaaS platforms.",
      location: "Palo Alto, CA",
      date: new Date("2025-07-28"),
      organizer_name: "SaaSNow",
      is_free: false,
      ticket_price: 25,
      registration_link: "https://saaslaunch.com",
    },
    {
      title: "Creative Writing Bootcamp",
      img: "https://example.com/event24.jpg",
      description: "Improve your storytelling and writing skills.",
      location: "Seattle, WA",
      date: new Date("2025-10-03"),
      organizer_name: "Writers Guild",
      is_free: true,
    },
    {
      title: "Ethical Hacking Workshop",
      img: "https://example.com/event25.jpg",
      description: "Learn white-hat hacking with hands-on sessions.",
      location: "Las Vegas, NV",
      date: new Date("2025-06-15"),
      organizer_name: "HackSecure",
      is_free: false,
      ticket_price: 80,
      registration_link: "https://hackworkshop.com",
    },
    {
      title: "Environmental Science Forum",
      img: "https://example.com/event26.jpg",
      description: "Scientific discussions on environmental challenges.",
      location: "Boulder, CO",
      date: new Date("2025-07-06"),
      organizer_name: "GreenLab",
      is_free: true,
    },
    {
      title: "Dance & Culture Night",
      img: "https://example.com/event27.jpg",
      description: "A celebration of music and dance from around the world.",
      location: "Orlando, FL",
      date: new Date("2025-08-15"),
      organizer_name: "Global Beats",
      is_free: false,
      ticket_price: 12,
      registration_link: "https://dancefest.com",
    },
    {
      title: "Mathematics in the Modern World",
      img: "https://example.com/event28.jpg",
      description: "Exploring math's role in modern technology and life.",
      location: "Cambridge, MA",
      date: new Date("2025-11-08"),
      organizer_name: "MathWorks",
      is_free: true,
    },
    {
      title: "Career Accelerator Bootcamp",
      img: "https://example.com/event29.jpg",
      description: "Boost your career with resume, interview, and soft skills training.",
      location: "Phoenix, AZ",
      date: new Date("2025-05-28"),
      organizer_name: "CareerLab",
      is_free: false,
      ticket_price: 45,
      registration_link: "https://careerboost.com",
    },
    {
      title: "Young Leaders Summit",
      img: "https://example.com/event30.jpg",
      description: "A conference for future changemakers and leaders.",
      location: "Washington, DC",
      date: new Date("2025-09-12"),
      organizer_name: "YouthRise",
      is_free: true,
    }
  ];
  export default allEvents;
  